# -*- coding: utf-8 -*-
"""05_if_estruturas_condicionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-uAHe8CFzkvDL54zqo-0mTK-H2Klrnh

# Exercícios com Estruturas Condicionais em Python
Notebook de exercícios sobre **estruturas condicionais (if, elif, else)** em Python.

Resolva cada exercício nas células de código abaixo. **Não há gabarito neste arquivo.**

## Exercício 1 — Validação de Investimento

Uma corretora quer automatizar uma recomendação básica de perfil de investimento.

Crie um programa que peça ao usuário o valor que ele deseja investir.

Regras:

1. Se o valor for menor que R$ 1.000,00 → mostrar: "Perfil iniciante: Sugerimos Tesouro Direto"

2. Se o valor estiver entre R$ 1.000,00 e R$ 5.000,00 (inclusive) → mostrar: "Perfil moderado: Sugerimos Fundos Imobiliários"

3. Se o valor for maior que R$ 5.000,00 → mostrar: "Perfil arrojado: Sugerimos Ações"

Dica: trate o input caso o usuário digite "R$" ou utilize vírgula.
"""

# Escreva sua solução aqui
valor = input("Digite o valor que deseja investir: ")
# trate o input caso o usuário digite "R$" ou utilize vírgula.
if valor.startswith("R$"):
  valor = valor.replace("R$", "")
valor = valor.replace(",", ".")
valor = float(valor)

if valor < 1000:
    print("Perfil iniciante: Sugerimos Tesouro Direto")
elif valor >= 1000 and valor <= 5000:
    print("Perfil moderado: Sugerimos Fundos Imobiliários")
else:
    print("Perfil arrojado: Sugerimos Ações")

print(valor)

"""## Exercício 2 — Controle de Acesso ao Sistema

Você possui a seguinte lista de administradores:

admins = ["ana@empresa.com", "guilherme@empresa.com", "felipe@empresa.com"]

Crie um programa que:

1. Peça o e-mail do usuário
2. Padronize o e-mail (letras minúsculas e sem espaços)
3. Verifique se o e-mail está na lista de administradores
4. Se estiver → mostrar: "Acesso liberado! Bem-vindo ao painel de controle"
5. Caso contrário → mostrar: "Acesso negado. Você não tem permissões de administrador"

"""

# Escreva sua solução aqui
admins = ["ana@empresa.com", "guilherme@empresa.com", "felipe@empresa.com"]
email = input("Digite o seu e-mail: ").lower().strip()
if email in admins:
    print("Acesso liberado! Bem-vindo ao painel de controle")
else:
    print("Acesso negado. Você não tem permissões de administrador")

"""## Exercício 3 — Cálculo de Desconto Progressivo

Um e-commerce aplica descontos automáticos no carrinho.

Crie um programa que receba o valor total da compra e aplique:

• Compras a partir de R$ 500,00 → 15% de desconto  
• Compras a partir de R$ 200,00 e abaixo de 500 → 10% de desconto  
• Compras abaixo de R$ 200,00 → sem desconto  

O programa deve exibir:

- o valor do desconto
- o valor final a pagar

Os valores devem ser exibidos formatados em R$.

"""

# Escreva sua solução aqui
valor_compras = float(input("Digite o valor da compra: "))
if valor_compras >= 500:
    desconto = 0.15
elif valor_compras >= 200:
    desconto = 0.1
else:
    desconto = 0
valor_desconto = valor_compras * desconto
valor_final = valor_compras - valor_desconto
print(f"O valor do desconto é: R$ {valor_desconto:.2f}\nO valor final a pagar é: R$ {valor_final:.2f}")

"""## Exercício 4 — Análise de Metas Combinadas

Uma empresa paga bônus quando duas metas são atingidas ao mesmo tempo.

Crie um programa que:

1. Peça as vendas do vendedor
2. Peça a meta individual do vendedor
3. Peça as vendas totais da loja
4. Peça a meta total da loja

Regras:

- Se o vendedor bater sua meta E a loja bater a meta da loja → bônus de 20% sobre as vendas do vendedor
- Caso contrário → bônus é zero

Mostrar a mensagem:

"Seu bônus este mês é de: R$ [valor]"

"""

# Escreva sua solução aqui
meta_loja = 100_000
meta_individual = 20_000

vendas_totais = float(input("Digite o valor das vendas totais: "))
vendas_vendedor = float(input("Digite o valor das vendas do vendedor: "))
if vendas_totais >= meta_loja and vendas_vendedor >= meta_individual:
    bonus = 0.2
else:
    bonus = 0
valor_bonus = vendas_vendedor * bonus
print(f"Seu bônus este mês é de: R$ {valor_bonus:,.2f}")

"""## Exercício 5 — Sistema de Triagem de E-mails

Crie um sistema simples para classificar e-mails por assunto.

O usuário deve digitar o assunto do e-mail.

Regras:

• Se aparecer "pagamento" ou "boleto" → mostrar: "Encaminhado para o Financeiro"

• Se aparecer "entrega" ou "atraso" → mostrar: "Encaminhado para a Logística"

• Caso contrário → mostrar: "Encaminhado para o Suporte Geral"

Dica: use o operador `in` para verificar se uma palavra está dentro do texto.

"""

# Escreva sua solução aqui
assunto_email = input("Digite o assunto do e-mail: ").lower()
if "pagamento" in assunto_email or "boleto" in assunto_email:
    print("Encaminhado para o Financeiro")
elif "entrega" in assunto_email or "atraso" in assunto_email:
    print("Encaminhado para a Logística")
else:
    print("Encaminhado para o Suporte Geral")